name: Generate Daily Security Reports

on:
  schedule:
    - cron: '15 6 * * *'   # 6:15 AM UTC
    - cron: '30 14 * * *'  # 2:30 PM UTC  
    - cron: '45 21 * * *'  # 9:45 PM UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  generate-report:
    runs-on: ubuntu-latest
    
    steps:
      - name: Generate and Submit Report
        run: |
          curl -f -X POST "${{ secrets.API_ENDPOINT }}" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.API_KEY }}" \
            -d '{}'
        env:
          # Add any environment variables your API needs
          NODE_ENV: production
